// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that analyzes chat poll results.
 *
 * - analyzePolls - A function that handles the chat poll analysis process.
 * - AnalyzePollsInput - The input type for the analyzePolls function.
 * - AnalyzePollsOutput - The return type for the analyzePolls function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzePollsInputSchema = z.object({
  pollQuestion: z.string().describe('The question asked in the poll.'),
  pollOptions: z.array(z.string()).describe('The options available in the poll.'),
  voteCounts: z.array(z.number()).describe('The number of votes for each option.'),
});
export type AnalyzePollsInput = z.infer<typeof AnalyzePollsInputSchema>;

const AnalyzePollsOutputSchema = z.object({
  summary: z.string().describe('A summary of the poll results, including sentiment and opinions.'),
  winningOption: z.string().describe('The option with the most votes.'),
  sentimentAnalysis: z.string().describe('An analysis of the overall sentiment expressed in the poll results.'),
});
export type AnalyzePollsOutput = z.infer<typeof AnalyzePollsOutputSchema>;

export async function analyzePolls(input: AnalyzePollsInput): Promise<AnalyzePollsOutput> {
  return analyzePollsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzePollsPrompt',
  input: {schema: AnalyzePollsInputSchema},
  output: {schema: AnalyzePollsOutputSchema},
  prompt: `You are an AI assistant that analyzes the results of chat polls.

  Given the following poll question, options, and vote counts, provide a summary of the poll results, identify the winning option, and analyze the overall sentiment expressed in the poll results.

  Poll Question: {{{pollQuestion}}}
  Poll Options: {{#each pollOptions}}{{{this}}}, {{/each}}
  Vote Counts: {{#each voteCounts}}{{{this}}}, {{/each}}

  Summary:
  Winning Option:
  Sentiment Analysis:`,
});

const analyzePollsFlow = ai.defineFlow(
  {
    name: 'analyzePollsFlow',
    inputSchema: AnalyzePollsInputSchema,
    outputSchema: AnalyzePollsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
