// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that analyzes chat poll results.
 *
 * - analyzeChatPoll - A function that handles the chat poll analysis process.
 * - AnalyzeChatPollInput - The input type for the analyzeChatPoll function.
 * - AnalyzeChatPollOutput - The return type for the analyzeChatPoll function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeChatPollInputSchema = z.object({
  pollQuestion: z.string().describe('The question asked in the poll.'),
  pollOptions: z.array(z.string()).describe('The options available in the poll.'),
  voteCounts: z.array(z.number()).describe('The number of votes for each option.'),
});
export type AnalyzeChatPollInput = z.infer<typeof AnalyzeChatPollInputSchema>;

const AnalyzeChatPollOutputSchema = z.object({
  summary: z.string().describe('A summary of the poll results, including sentiment and opinions.'),
  winningOption: z.string().describe('The option with the most votes.'),
  sentimentAnalysis: z.string().describe('An analysis of the overall sentiment expressed in the poll results.'),
});
export type AnalyzeChatPollOutput = z.infer<typeof AnalyzeChatPollOutputSchema>;

export async function analyzeChatPoll(input: AnalyzeChatPollInput): Promise<AnalyzeChatPollOutput> {
  return analyzeChatPollFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeChatPollPrompt',
  input: {schema: AnalyzeChatPollInputSchema},
  output: {schema: AnalyzeChatPollOutputSchema},
  prompt: `You are an AI assistant that analyzes the results of chat polls.

  Given the following poll question, options, and vote counts, provide a summary of the poll results, identify the winning option, and analyze the overall sentiment expressed in the poll results.

  Poll Question: {{{pollQuestion}}}
  Poll Options: {{#each pollOptions}}{{{this}}}, {{/each}}
  Vote Counts: {{#each voteCounts}}{{{this}}}, {{/each}}

  Summary:
  Winning Option:
  Sentiment Analysis:`, // Use Handlebars here
});

const analyzeChatPollFlow = ai.defineFlow(
  {
    name: 'analyzeChatPollFlow',
    inputSchema: AnalyzeChatPollInputSchema,
    outputSchema: AnalyzeChatPollOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
