// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that generates dynamic message animations based on the tone of the message.
 *
 * - generateAnimation - A function that handles the message animation generation process.
 * - GenerateAnimationInput - The input type for the generateAnimation function.
 * - GenerateAnimationOutput - The return type for the generateAnimation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAnimationInputSchema = z.object({
  message: z.string().describe('The message content.'),
});
export type GenerateAnimationInput = z.infer<typeof GenerateAnimationInputSchema>;

const GenerateAnimationOutputSchema = z.object({
  animationType: z.string().describe('The type of animation to use for the message.'),
  animationData: z.any().describe('Data needed to render the animation.'),
});
export type GenerateAnimationOutput = z.infer<typeof GenerateAnimationOutputSchema>;

export async function generateAnimation(input: GenerateAnimationInput): Promise<GenerateAnimationOutput> {
  return generateAnimationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'dynamicMessageAnimationPrompt',
  input: {schema: GenerateAnimationInputSchema},
  output: {schema: GenerateAnimationOutputSchema},
  prompt: `You are an expert in creating dynamic message animations based on the tone of the message.

  Analyze the following message and determine the most appropriate animation type and data to use.

  Message: {{{message}}}

  Consider these animation types:

  -   **Happy/Excited**: Bouncing, scaling, color shifting, confetti.
  -   **Sad/Disappointed**: Fading, shrinking, grayscale.
  -   **Angry/Frustrated**: Shaking, glitching, distortion.
  -   **Neutral/Informative**: Subtle pulsing, sliding, highlighting.

  Return JSON for the animation type and data.
  `,
});

const generateAnimationFlow = ai.defineFlow(
  {
    name: 'generateAnimationFlow',
    inputSchema: GenerateAnimationInputSchema,
    outputSchema: GenerateAnimationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
