// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that detects the mood of a chat message and recommends a theme and background music.
 *
 * - getThemeAndMusic - A function that handles the mood detection and theme/music recommendation process.
 * - GetThemeAndMusicInput - The input type for the getThemeAndMusic function.
 * - GetThemeAndMusicOutput - The return type for the getThemeAndMusic function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetThemeAndMusicInputSchema = z.object({
  message: z.string().describe('The chat message to analyze.'),
});
export type GetThemeAndMusicInput = z.infer<typeof GetThemeAndMusicInputSchema>;

const GetThemeAndMusicOutputSchema = z.object({
  mood: z.string().describe('The detected mood of the message (e.g., happy, sad, angry).'),
  theme: z.object({
      primary: z.string().describe("The primary color in HSL format, e.g., '283 100% 41%'"),
      background: z.string().describe("The background color in HSL format, e.g., '283 100% 8%'"),
      accent: z.string().describe("The accent color in HSL format, e.g., '181 100% 74%'")
  }).describe('A suggested theme for the app based on the mood, with colors in HSL format without the hsl() wrapper.'),
  music: z.string().describe('A suggested background music track based on the mood.'),
});
export type GetThemeAndMusicOutput = z.infer<typeof GetThemeAndMusicOutputSchema>;

export async function getThemeAndMusic(input: GetThemeAndMusicInput): Promise<GetThemeAndMusicOutput> {
  return getThemeAndMusicFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getThemeAndMusicPrompt',
  input: {schema: GetThemeAndMusicInputSchema},
  output: {schema: GetThemeAndMusicOutputSchema},
  prompt: `You are an AI assistant that analyzes the mood of a chat message and suggests a theme and background music to match the mood.

Analyze the following message and determine its mood. Then, suggest a theme with specific HSL color values and a background music track that would be appropriate for that mood.

Message: {{{message}}}

Respond in JSON format. For the HSL values, provide them as strings like 'H S% L%'.
For example:
- primary: '210 40% 96.1%'
- background: '222.2 84% 4.9%'
- accent: '217.2 91.2% 59.8%'
`,
});

const getThemeAndMusicFlow = ai.defineFlow(
  {
    name: 'getThemeAndMusicFlow',
    inputSchema: GetThemeAndMusicInputSchema,
    outputSchema: GetThemeAndMusicOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
