// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Automatically detects plans and commitments made within chats and suggests adding them to the calendar.
 *
 * - smartSchedulingAssistant - A function that handles the smart scheduling assistant process.
 * - SmartSchedulingAssistantInput - The input type for the smartSchedulingAssistant function.
 * - SmartSchedulingAssistantOutput - The return type for the smartSchedulingAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SmartSchedulingAssistantInputSchema = z.object({
  chatHistory: z
    .string()
    .describe('The chat history to analyze for potential calendar events.'),
  userPreferences: z
    .string()
    .optional()
    .describe('Optional user preferences for scheduling events.'),
});
export type SmartSchedulingAssistantInput = z.infer<
  typeof SmartSchedulingAssistantInputSchema
>;

const SmartSchedulingAssistantOutputSchema = z.object({
  events: z.array(
    z.object({
      title: z.string().describe('The title of the event.'),
      startTime: z.string().describe('The start time of the event in ISO format.'),
      endTime: z.string().optional().describe('The end time of the event in ISO format.'),
      description: z.string().optional().describe('A description of the event.'),
    })
  ).describe('An array of detected events to add to the calendar.'),
});
export type SmartSchedulingAssistantOutput = z.infer<
  typeof SmartSchedulingAssistantOutputSchema
>;

export async function smartSchedulingAssistant(
  input: SmartSchedulingAssistantInput
): Promise<SmartSchedulingAssistantOutput> {
  return smartSchedulingAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'smartSchedulingAssistantPrompt',
  input: {schema: SmartSchedulingAssistantInputSchema},
  output: {schema: SmartSchedulingAssistantOutputSchema},
  prompt: `You are a smart scheduling assistant that analyzes chat history to identify potential calendar events.

  Analyze the following chat history and extract any events or commitments that should be added to the user's calendar.  If specific times are mentioned, extract them.  If no specific times are mentioned, but a future commitment is made, set the time to 9am of that day.  Assume the current year if the year is not explicitly mentioned.

  Consider any user preferences provided to better understand their scheduling habits.

  Output the events as a JSON array of objects, with each object containing the event title, start time (ISO format), optional end time (ISO format), and description.

  Chat History:
  {{chatHistory}}

  User Preferences:
  {{userPreferences}}
  `,
});

const smartSchedulingAssistantFlow = ai.defineFlow(
  {
    name: 'smartSchedulingAssistantFlow',
    inputSchema: SmartSchedulingAssistantInputSchema,
    outputSchema: SmartSchedulingAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
